version: "4.2"
services:
  postgres:
    container_name: postgres
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: P0stgres@dm1n
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  axonserver:
    container_name: axonserver
    image: axoniq/axonserver:2023.2.2
    restart: always
    ports:
      - "8024:8024"
      - "8124:8124"
volumes:
  postgres_data:
    driver: local